http_c4c:
  build: ./apache
  privileged: true
  restart: always
  hostname: http_c4c
  container_name: http_c4c
  ports:
   - "80:80"
   - "443:443"
  links:
   - tomcat_c4c:tomcat_c4c
   - tomcat_sesame_c4c:tomcat_sesame_c4c
#   - cron_batch_c4c:cron_batch_c4c
   
tomcat_c4c:
  build: ./tomcat
  privileged: true
  restart: always
  hostname: tomcat_c4c
  container_name: tomcat_c4c
  links:
   - mongo_c4c:mongo_c4c
   
mongo_c4c:
  build: ./mongo
  privileged: true
  restart: always  
  hostname: mongo_c4c
  container_name: mongo_c4c
  ports:
   - "27017:27017"
   
tomcat_sesame_c4c:
  build: ./sesame
  privileged: true
  restart: always
  hostname: tomcat_sesame_c4c
  container_name: tomcat_sesame_c4c
  ports:
   - "8080:8080"

#cron_batch_c4c:
#  build: ./cron
#  privileged: true
#  restart: always
#  hostname: cron_batch_c4c
#  container_name: cron_batch_c4c
#  links:
#   - tomcat_c4c:tomcat_c4c
#   - tomcat_sesame_c4c:tomcat_sesame_c4c
#   - mongo_c4c:mongo_c4c
